config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#Home'

  get 'galleries' => 'static_pages#Galleries'

  get 'about' => 'static_pages#About'

  get 'contact' => 'static_pages#Contact'

  get 'investment' => 'static_pages#Investment'

  get 'blog' => 'static_pages#Blog'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def Home
  end

  def Galleries
  end

  def About
  end

  def Contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_email.html.erb
<div class = "row">
    <div class = "col-md-6 col-md-offset-3">

        <%= form_tag '/path' do%>
        Email : </br><%= text_field_tag 'email',  ''%></br>
        subject: </br><%= text_field_tag 'subject', ''%></br>
        Body:<%= text_area_tag 'body', ''%>
        <%= submit_tag "submit",:value => "submit", class: "btn btn-primary" %>
        <%end%>
    </div>
</div>

app/views/layouts/_flip.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
  
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <%= image_tag('car1.jpg')%>
      </div>
  
      <div class="item">
        <%= image_tag('car2.jpg')%>
      </div>
  
      <div class="item">
        <%= image_tag('car3.jpg')%>
      </div>
    </div>
  
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <i class="fas fa-chevron-left"></i>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <i class="fas fa-chevron-right"></i>
    </a>
  </div>

app/views/layouts/_grid.html.erb
<div class = "container">
    <div class = "row animatable fadeIn">
        <div class = "col span-12 dark">
            <div class = "portfolio" style="width: 344px;height: 344px">
                    <%= image_tag("1.png") %>
            </div>
        </div>
        <div class = "col span-12 dark">
            <div class = "portfolio" style="width: 344px;height: 344px">
                    <%= image_tag("2.png") %>
            </div>
        </div>
        <div class = "col span-12 dark">
                <div class = "portfolio" style="width: 344px;height: 344px">
                        <%= image_tag("3.png") %>
                </div>
            </div>
        </div>
    <div class = "row animatable fadeIn">
            <div class = "col span-12 dark">
                <div class = "portfolio" style="width: 344px;height: 344px">
                        <%= image_tag("4.png") %>
                </div>
            </div>
            <div class = "col span-12 dark">
                <div class = "portfolio" style="width: 344px;height: 344px">
                        <%= image_tag("5.png") %>
                </div>
            </div>
            <div class = "col span-12 dark">
                    <div class = "portfolio" style="width: 344px;height: 344px">
                            <%= image_tag("6.png") %>
                    </div>
                </div>    
        </div>
    <div class = "row final animatable fadeIn">
        <div class = "col span-12 dark">
            <div class = "portfolio" style="width: 344px;height: 344px">
                    <%= image_tag("7.png") %>
            </div>
        </div>
        <div class = "col span-12 dark">
            <div class = "portfolio" style="width: 344px;height: 344px">
                    <%= image_tag("8.png") %>
            </div>
        </div>
        <div class = "col span-12 dark">
                <div class = "portfolio" style="width: 344px;height: 344px">
                        <%= image_tag("9.png") %>
                </div>
            </div>
        </div> 
        </div> 
</div>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top">
    <div class = "container header">
        <%= link_to "Amanda Louise Photography", root_path, class: 'logo'%>
        <div class = "slogan">
            Passionate & Authentic Photography
        </div>
        <nav>
           <ul class = "nav navbar-nav navbar-center">
           <li><%= link_to "Home", root_path %></li>
           <li><%= link_to "Galleries", galleries_path %></li>
           <li><%= link_to "Investment", investment_path %></li>
           <li><%= link_to "Blog", blog_path %></li>
           <li><%= link_to "Contact", contact_path %></li>
           <li><a href="javascript:void(0);" style="font-size:15px;" class="ham-icon" onclick="myFunction()">&#9776;</a></li>
        </ul> 
        </nav>
    </div>
</header>

app/views/layouts/_topcar.html.erb
<div class = "conatainer-fluid">
<div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
                <div class="active item one"></div>
                <div class="item two"></div>
                <div class="item three"></div>
        </div>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amanda Louise Photography</title>
    <link href="https://fonts.googleapis.com/css?family=Assistant|Rosario" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'layouts/header' %>
    <div class = 'container-fluid content'>
    <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/About.html.erb
<h1>StaticPages#About</h1>
<p>Find me in app/views/static_pages/About.html.erb</p>

app/views/static_pages/Blog.html.erb
<h1>StaticPages#Blog</h1>
<p>Find me in app/views/static_pages/Blog.html.erb</p>

app/views/static_pages/Contact.html.erb
<h1>StaticPages#Contact</h1>
<p>Find me in app/views/static_pages/Contact.html.erb</p>

app/views/static_pages/Galleries.html.erb
<h1>StaticPages#Galleries</h1>
<p>Find me in app/views/static_pages/Galleries.html.erb</p>

<%= render 'layouts/grid'%>

app/views/static_pages/Home.html.erb
<%= render 'layouts/flip'%>   
<div class = "welcome">
        <div class = "text">
                <span>Passionate & Authentic Photography</span>
        </div>
</div>
<div class = "about-home">
        <div class = "about-amanda">
                <span>About Amanda</span>
        </div>
</div>
<div class = "reviews">
        <div class = "section-1">
                <div class ="box-1">
                        <div class ="quote-1">
                                <span>"You just have to live and life will give you pictures" </br> </br>- Henry Cardier Bresson</span>
                        </div>
                </div>
        </div>
        <div class = "section-2">
                <div class ="box-2">
                        <div class ="quote-2">
                                <span>"Amanda is one of the most genuinely sweet and loving people I have ever met. With the help of her wonderful assistant (her husband) she took my husband and I's wedding photos in October of 2014 and did such a wonderful job we have recommended her many times to others! She is so easy to work with and truly loves what she does and gives you the wonderful quality photos you're looking for on your special day. I HIGHLY recommended Amanda to take photos for any occasion. Beautiful photos, beautiful person and great overall experience!" </br> </br>-Heather S, Orlando FL</span>
                        </div>
                </div>

        </div>
        <div class = "section-3">
        </div>
</div>
<div class = "recent-blog"></div>

app/views/static_pages/Investment.html.erb
<h1>StaticPages#Investments</h1>
<p>Find me in app/views/static_pages/Investments.html.erb</p>